// Set this variable to a starting Fahrenheit temperature...
var fahrenheit = 32;

// Enter conversion code below...
var fahrenheitToCelsius = ...;
var fahrenheitToKelvin = ...;

// Enter console.log statements below...

// Repeat the above for Celsius and Kelvin...
var celsius = 0;
var kelvin = 273.15;
